//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyLaundering.Api.Crosscutting.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyLaundering.Api.Crosscutting.Globalization.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro la actividad.
        /// </summary>
        public static string ActivityNotFound {
            get {
                return ResourceManager.GetString("ActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron unidades de negocio.
        /// </summary>
        public static string BussinessUnitNotFound {
            get {
                return ResourceManager.GetString("BussinessUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron recuperar las alertas.
        /// </summary>
        public static string CantAlertRecovery {
            get {
                return ResourceManager.GetString("CantAlertRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo registrar la novedad.
        /// </summary>
        public static string CantRegisterNews {
            get {
                return ResourceManager.GetString("CantRegisterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo guardar la novedad.
        /// </summary>
        public static string CantSaveNews {
            get {
                return ResourceManager.GetString("CantSaveNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el caso.
        /// </summary>
        public static string CantUpdateCase {
            get {
                return ResourceManager.GetString("CantUpdateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el documento en las novedades.
        /// </summary>
        public static string CantUpdateNewsDocument {
            get {
                return ResourceManager.GetString("CantUpdateNewsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el mail para la novedad.
        /// </summary>
        public static string CantUpdateNewsMail {
            get {
                return ResourceManager.GetString("CantUpdateNewsMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo guardar la unidad de negocio.
        /// </summary>
        public static string CantUpdatePersonBusinessUnit {
            get {
                return ResourceManager.GetString("CantUpdatePersonBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron grupos de casos.
        /// </summary>
        public static string CaseGroupNotFound {
            get {
                return ResourceManager.GetString("CaseGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso no encontrado.
        /// </summary>
        public static string CaseNotFound {
            get {
                return ResourceManager.GetString("CaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron casos.
        /// </summary>
        public static string CasesNotFound {
            get {
                return ResourceManager.GetString("CasesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron tipos de casos.
        /// </summary>
        public static string CaseTypeNotFound {
            get {
                return ResourceManager.GetString("CaseTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento incluido en lista gris.
        /// </summary>
        public static string DocumentInGrayList {
            get {
                return ResourceManager.GetString("DocumentInGrayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento vinculado a varios casos.
        /// </summary>
        public static string DocumentInMultipleCases {
            get {
                return ResourceManager.GetString("DocumentInMultipleCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el tipo de carta.
        /// </summary>
        public static string DocumentLetterTypeNotFound {
            get {
                return ResourceManager.GetString("DocumentLetterTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento no encontrado.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo vincular el documento a la persona en lista gris.
        /// </summary>
        public static string GrayListDocumentNotSaved {
            get {
                return ResourceManager.GetString("GrayListDocumentNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo guardar la persona en lista gris.
        /// </summary>
        public static string GrayListPersonNotSaved {
            get {
                return ResourceManager.GetString("GrayListPersonNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron localidades.
        /// </summary>
        public static string LocationsNotFound {
            get {
                return ResourceManager.GetString("LocationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el tipo de mail.
        /// </summary>
        public static string MailTypeNotFound {
            get {
                return ResourceManager.GetString("MailTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraton documentos para la novedad.
        /// </summary>
        public static string NewsDocumentsNotFound {
            get {
                return ResourceManager.GetString("NewsDocumentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron mails para la novedad.
        /// </summary>
        public static string NewsMailsNotFound {
            get {
                return ResourceManager.GetString("NewsMailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron novedades.
        /// </summary>
        public static string NewsNotFound {
            get {
                return ResourceManager.GetString("NewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron novedades en el caso.
        /// </summary>
        public static string NewsNotFoundInCase {
            get {
                return ResourceManager.GetString("NewsNotFoundInCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron motivos.
        /// </summary>
        public static string NewsReasonsNotFound {
            get {
                return ResourceManager.GetString("NewsReasonsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de novedad no encontrado.
        /// </summary>
        public static string NewsTypeNotFound {
            get {
                return ResourceManager.GetString("NewsTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron personas.
        /// </summary>
        public static string PersonsNotFound {
            get {
                return ResourceManager.GetString("PersonsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron riesgos.
        /// </summary>
        public static string RiskNotFound {
            get {
                return ResourceManager.GetString("RiskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron estados.
        /// </summary>
        public static string StatesNotFound {
            get {
                return ResourceManager.GetString("StatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron estados de caso.
        /// </summary>
        public static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron vehiculos.
        /// </summary>
        public static string VehiclesNotFound {
            get {
                return ResourceManager.GetString("VehiclesNotFound", resourceCulture);
            }
        }
    }
}
