CREATE TABLE [dbo].[Person] (
    [PersonId]						INT	IDENTITY (1, 1) NOT NULL,
    [PersonKey]						VARCHAR (100) NOT NULL,
    [BusinessUnitId]				INT NOT NULL,
    [Cuit]							VARCHAR (50) NOT NULL,
    [LastName]						VARCHAR (200) NOT NULL,
    [FirstName]						VARCHAR (200) NOT NULL,
    [Active]						BIT NOT NULL,
    [CreationDate]					DATETIME2 (2) NOT NULL,
    [UpdateDocumentDate]			DATETIME2 (2) NULL,
    [Pep]							BIT NULL,
    [PepSystem]						BIT NULL,
    [RegisterUIF]					BIT NULL,
    [Terrorist]						BIT NULL,
    [CheckListDate]					DATETIME2 (2) NULL,
    [PersonType]					CHAR (1) NULL,
    [Mail]							VARCHAR (200) NULL,
    [ActivityId]					INT NULL,
    [LocationId]					INT NULL,
    [Address]						VARCHAR (200) NULL,
    [OfficialTypeId]				VARCHAR (5) NULL,
    [TaxId]							INT NULL,
    [Nationality]					VARCHAR (100) NULL,
    [BirthDate]				        DATETIME2 (2) NULL,
    [Maritalstatus]					VARCHAR (100) NULL,
    [PhoneNumber]					VARCHAR (200) NULL,
    [ThirdParty]					BIT NOT NULL,
    [GroupCode]						INT NULL,
    [Group]							BIT NOT NULL,
    [ZipCode]						INT NULL,
    [RegistrationDate]				DATETIME2 (2) NULL,
    [RegistrationNumber]			VARCHAR (100) NULL,
	--[Audit_Insert_User]				VARCHAR (50) NOT NULL,
	--[Audit_Insert_Date]				DATETIME2 (7) NOT NULL,
    --[Audit_Update_User]				DATETIME2 (7) NOT NULL,
    --[Audit_Update_Date]				VARCHAR (50) NOT NULL,
    CONSTRAINT [FK_Person] PRIMARY KEY CLUSTERED ([PersonId] ASC),
    CONSTRAINT [FK_Person_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [dbo].[Activity] ([ActivityId]),
    CONSTRAINT [FK_Person_Location] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([LocationId]),
	CONSTRAINT [FK_Person_BusinessUnit] FOREIGN KEY ([BusinessUnitId]) REFERENCES [dbo].[BusinessUnit] ([BusinessUnitId])
);

